steps:
  - name: ':docker: Build and push Docker image to tink-containers'
    timeout_in_minutes: 10
    command: |
      # Build
      export VERSION=$(date -u +"%Y-%m-%dT%H-%M-%SUTC") # try using git commit hash
      docker build -t xgboost:$VERSION .

      # Tag and push image with version number to repository
      docker tag xgboost:$VERSION gcr.io/tink-containers/xgboost:$VERSION
      gcloud docker -- push gcr.io/tink-containers/xgboost:$VERSION